cli/src/lib/compile.js
examples/simple-app/yarn.lock

There are two issues still existing after this PR - 
1. If there is a compilation error **on startup**, we get a FATAL code and have to abort (which we do properly now).  We should continue to watch for changes until it gets fixed
2. When we do abort, the CRA start script continues to run in the background and gets orphaned by the parent process

fix: show compilation errors when watching for changes

---

cli/package.json

Publishes have been silently failing (see dhis2/cli#131) since 1.2.0 because of the comment dependency in package.json.  I moved the comment out of the dependencies map, which should work fine.

fix: remove publish-breaking comment from package.json

---

examples/simple-app/yarn.lock
shell/src/App.js

I switched the AppAdapter to a React.Lazy component a while back.  This has the advantage of code-splitting the bundle, so that we can analyze what's in the adapter vs the shell itself.  However, it had the consequence of causing the Headerbar to wait until the entire application has loaded before rendering.  This meant that, for applications with moderate bundle sizes like the Query Playground and also in low-bandwidth situations the entire page would flash "blank white" for a noticeable duration.
This change reverts the Adapter code-splitting, so that the shell displays the adapter (including the headerbar) on first render.  It also adds displays full-page screen cover and loading spinner while the app bundle loads, rather than an empty div.  You can test this behavior by setting "slow …

fix: don't dynamically load the app adapter (prevent blank flash)

---

cli/package.json
cli/src/commands/start.js
cli/src/lib/shell/env.js
docs/scripts/start.md
examples/simple-app/yarn.lock
shell/adapter/yarn.lock
yarn.lock

This adds a `--port` switch to the `start` command and also corrects the behavior when the specified port (by CLI flag, env var, or default 3000) is occupied - instead of silently failing and waiting forever, it warns the user that the port is in use and selects the next available port sequentially to run the dev server.

fix: detect an occupied port and find an open one

---

cli/config/rollup.config.js
examples/simple-app/yarn.lock
shell/adapter/yarn.lock

We should use the `browser` field in package.json for dependency resolution, otherwise we might get server code (for packages that distribute both under the same name, like `styled-components`)
> NOTE: The yarn.lock changes in the example app and shell adapter are unrelated, just residual from the previous version bump

fix: use browser field in package.json if it exists

---

examples/simple-app/yarn.lock
shell/adapter/yarn.lock
shell/yarn.lock

The following error (cryptic at best) occurred because `yarn.lock` wasn't correctly updated in the shell and shell adapter.  This was problematic specifically because we run `yarn install --frozen-lockfile --prefer-offline`, which means the lockfile can't be out of date.
```
error Couldn't find package "@dhis2/ui-core@^3.12.0" required by "@dhis2/app-adapter@file:./adapter" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@dhis2/ui-widgets@^2.0.0" required by "@dhis2/app-adapter@file:./adapter" on the "npm" registry.
at MessageError.ExtendableBuiltin (/Users/awm/.yarn/lib/cli.js:721:66)
at new MessageError (/Users/awm/.yarn/lib/cli.js:750:123)
at PackageRequest.<anonymous> …
```

fix: update yarn.lock, otherwise install fails with cryptic error

---

examples/simple-app/yarn.lock
package.json
shell/adapter/package.json
shell/adapter/yarn.lock
shell/yarn.lock

Also fixes the build process to ensure `shell/yarn.lock` is correctly updated

fix: upgrade Headerbar to 2.0.1, don't break on older servers

---

examples/simple-app/yarn.lock
shell/adapter/src/index.js
shell/adapter/yarn.lock

We mistakenly only rendered a DataProvider, which meant that the `useContext` hook returned invalid information (`baseUrl: '..'`) instead of being initialized by the app shell.

fix: use Provider instead of DataProvider

---

cli/package.json
shell/adapter/package.json
shell/adapter/src/AuthBoundary/LoginModal.js
shell/adapter/yarn.lock
shell/package.json
shell/yarn.lock
yarn.lock

This is needed for DV where the new options UI uses features and fixes in `@dhis2/ui-core` introduced from version 4.
BREAKING CHANGE: This will break applications expecting the `ui-core` v3 API

chore(deps): upgrade @dhis2/ui-core to 4.1.1 and @dhis2/ui-widgets to 2.0.4

---

shell/.eslintrc.js

Fixes #197
This adds an eslint config to the shell root which will automatically detect a top-level `.eslintrc.js` file and load it, or will use `react-app` as a fallback.

fix: add an eslint config to shell, falling back to react-app defaults

---

cli/config/babel.config.js

When running `cli-app-scripts test` in an app, the line:
extends: './app.babel.config'
Incorrectly resolves from the current working directory:
Cannot find module './app.babel.config' from '/home/varl/dev/dhis2/apps/usage-analytics'
We can use `path.resolve` + `__dirname`[1] to resolve the absolute path
of the `app.babel.config.js` file relatively to `babel.config.js`.
[1] https://nodejs.org/api/globals.html#globals_dirname

fix: resolve the absolute path to the current directory

---

cli/src/commands/i18n.js
cli/src/lib/i18n/extract.js
cli/src/lib/i18n/generate.js
cli/src/lib/i18n/helpers.js

Fixes #268 
This also cleans up some of the i18n code that was ported from the `d2-i18n-[extract|generate]` libraries

fix: don't generate useless empty files if no translatable strings found

---

cli/src/lib/compiler/compileLibrary.js
cli/src/lib/paths.js

This removes the devOut path and usage of it, instead opting for
building the development build and production build into the same
folder: ./build.
For libraries in monorepo situations this is important as they will look
up the main or module key in the package.json file, which is usually set
to e.g. ./build/{cjs,es}/lib.js when using the cli-app-scripts to build
the lib.

fix(cli-app-scripts): use the same build dir for modes

---

adapter/src/styles.js

Fixes the height issue in Safari for DV (https://jira.dhis2.org/browse/DHIS2-8277) by explicitly setting the height of the app to `100%`.
Correct height:

fix: height in safari (DHIS2-8277)

---

cli/package.json
yarn.lock

`styled-jsx` needs to be included as a dependency of `d2-app-scripts` to support styled-jsx babel transpilation - in some cases, it isn't properly hoisted from app-shell.

fix: explicitly include styled-jsx as cli dependency

---

adapter/src/AuthBoundary/LoginModal.js

On the DHIS2 user registration page we require a minimum of 4 characters when selecting a username.  However, in the user management app the minimum is 2 characters.
This change allows users created in the latter interface to log in through the AppShell login dialog.

fix: allow login username or password to be shorter than 4 chars

---

cli/config/app.babel.config.js
cli/config/jest.config.js
cli/config/jest.styled-jsx-css.mock.js

In test environments we should:
1. Use `styled-jsx/babel-test` instead of `styled-jsx/babel`
2. Mock the `styled-jsx/css` function as a no-op
This results in clean snapshot output without randomly-generated `jsx-#####` which change whenever any css changes.  See [the styled-jsx README](https://github.com/zeit/styled-jsx/blob/master/readme.md#rendering-in-tests)

fix: don't generate styled-jsx randomized classes in jest snapshots

---

docs/getting-started.md

Hi 👋- hope you all having a good day! 
I am opening this little PR where I am adding a sentence that prompts the reader to the deep dive article from the developers docs. 
After reading the docs for the first time and as someone who never heard of the term application platform before I had the feeling that I didnt grasp the idea very well. I find that this article has a very good and short overview of what the Application Platform is, how it works and how can someone use it. 
This PR has no issue related to it but it emerged after a talk I had with @amcgee. Let me know your thoughts on this and your feedback.

docs: adds the article with the Application Platform overview

---

cli/src/lib/i18n/helpers.js

Key differences were being incorrectly detected, using `some` instead of `all` - this resulted in change detection only when the **number** of strings changed, rather than the content of any of those keys.

fix: correctly detect changes in i18n string extraction

---

cli/config/babel.config.js
cli/config/rollup.config.js

Typescript was supported in the compiler, but not in rollup so it didn't work for libraries.  Eventually we may want to include the default tsconfig.json here, but for the moment only https://github.com/dhis2/app-runtime uses it.

fix: support typescript source files in library builds

---

cli/src/lib/i18n/extract.js

The i18next-scanner parser will set default values for a string if they are provided (including for plurals). 
This fix will copy any default values into the json that is used to generate the en.pot file.
Then we can have code in our apps like this:
```
const likes = i18n.t(
'{{count}} likes',
{ 
count: numLikes,
defaultValue: '{{count}} like',
defaultValue_plural: '{{count}} likes'
});
```
This results in the following in the en.pot file:
```
msgid "{{count}} likes"
msgid_plural "{{count}} likes"
msgstr[0] "{{count}} like"
msgstr[1] "{{count}} likes"
```
Ultimately in the app, we end up with these strings: `1 like` and `2 likes` as default.

fix: keep default values that may have been set

---

cli/src/lib/compiler/compileApp.js

Should be `reporter.debugErr`, see https://github.com/dhis2/cli-helpers-engine/blob/v1.5.0/lib/reporter.js#L29

fix: fix erroneous call to reporter.debugError

---

adapter/src/AuthBoundary/LoginModal.js

This will add unique `data-test` props to the login form so that logging in can easily be automated in in-browser tests.

fix: add login form data-test props

---

cli/package.json
docs/usage/dependencies.md
yarn.lock

fix(dependency): update babel-preset-env

---

cli/src/commands/build.js

Closes #458 
I looked around, but this seems to be the only place where this pattern was used. I chose a separate var instead of using parentheses to clarify the intent, so that later on someone doesn't accidentally remove the parentheses.

fix: base url should be overridden with env var if present

---

cli/src/lib/generateManifest.js

Relates to dhis2/dhis2-core#6111 - add `core_app` flag to `manifest.webapp` so that the Core knows it is an intentional override.

feat: add core_app flag to app manifest

---

cli/src/lib/generateManifest.js
cli/src/lib/paths.js

This generates a new config file `d2.config.json` from the compiled [application config](https://platform.dhis2.nu/#/config/d2-config-js-reference) (merge of `package.json` and `d2.config.js`).  The `.json` file is placed at the root of the application output, next to `manifest.webapp`, which it will eventually replace.  The data in this config file is necessary to enforce immutable application slugs, parse version numbers, and other things when publishing to the App Hub.
Here is a sample `d2.config.json` output generated from `examples/simple-app` :
```json
{
"name": "simple-app",
"title": "Simple Example App",
"description": "This is a simple example application",
"standalone": true,
"type": "app",
"version": "1.0.0",
"author": {
"name": "Austin McGee",
"email": "austin@dhis2.org"
}
} …
```

feat: generate d2.config.json from d2.config.js

---

cli/package.json
yarn.lock

There is an open [bug in styled-jsx/babel](https://github.com/vercel/styled-jsx/issues/695) introduced in 3.3.3 which causes invalid js output.  Until that issue is fixed, pin our version of styled-jsx to 3.3.2 (for compilation, runtime can still track later versions)

fix: pin styled-jsx@3.3.2 to avoid styled-jsx/babel bug

---

adapter/src/utils/useLocale.js

This is a very minor under-the-hood change.
Previously, all code-split chunks in an application used a numeric id + hash as their filename.  This is technically fine, but it becomes hard to tell which chunks are important when there are 100+ moment locale chunks each 5-20kb in size and just a few "core" chunks numbered something like `135`, `136`, and `137` which contain the actual application code.
This change adds a webpack magic comment which results in moment locale chunks generated into the `static/js/moment-locales` directory and named with the tag of the relevant locale instead of a random number (`fr.HASH.js` instead of `13.HASH.js`)

fix: namespace code-split moment locale chunks to separate them from app chunks

---

cli/src/lib/generateManifest.js
examples/simple-app/d2.config.js

Generates `app_hub_id` in `webapp.manifest` (and `id` in `d2.config.json`) from `id` in `d2.config.js`

feat: add support for generating manifest app_hub_id from d2.config id [LIBS-132]

---

cli/src/lib/validators/validatePackageExports.js

This change makes it so that we resolve the entry-point relatively to
the src folder, so src/react/index.js becomes react/index.js.
This resolves an issue when the library entry-point is not defined as
src/index.js.
So for example src/react/index.js will fail to build because we only
used the basename (index.js) to construct the build entry-point path, so
the react part of the path disappears from the expected path.
We got build/es/index.js when we should have gotten
build/es/react/index.js.
Since we force users of app-scripts to put their source code under
'src' (compiler/compile.js:15), we can safely assume that the configured
entry-point can be resolved relatively to the src directory and grab
everything to the right and build the path to the target directory, e.g. …

fix: allow for nested entry-points under src

---

adapter/src/components/AuthBoundary.js
adapter/src/utils/useLocale.js

Because we set the locale state in a `useEffect`, there was a subtle race condition bug which could cause the application to render before the locale is set.  When this happens, strings in the app are not correctly translated because the locale hasn't yet been switch from English to whatever the user has selected.

fix: don't render application until we are sure the locale is initialized

---

adapter/src/components/AuthBoundary.js

The change to wait for locale initialization resulted in the LoginModal never rendering, this fixes that issue.
Thanks @mediremi for flagging this

fix: show login modal before locale is loaded

---

adapter/package.json
shell/package.json
yarn.lock

Related to [DHIS2-9893](https://jira.dhis2.org/browse/DHIS2-9893)
This bumps @dhis2/app-platform to use ui v6 which should have all the latest and greatest headerbar fixes.
BREAKING CHANGE: applications must use `@dhis2/ui@^6.5.3`

feat: upgrade to @dhis2/ui v6 and bump other dependency versions

---

cli/src/commands/build.js
cli/src/commands/i18n.js
cli/src/commands/start.js
cli/src/lib/i18n/extract.js
cli/src/lib/i18n/generate.js

Currently, when generating `i18n` strings (either as a result of `d2-app-scripts start` or `d2-app-scripts extract`), a message in the format below is logged:
```
Writing N language strings to .//home/user/some/path/app-being-developed/i18n/en.pot...
```
This PR ensures that the path to `en.pot` logged is relative to the current working directory, resulting in the more consice:
```
Writing N language strings to ./en.pot...
```

fix: respect --cwd argument when generating/extracting translations

---

cli/src/lib/i18n/extract.js

A default value will be set for every string. if no default value is specifically provided, then the key will be used.  The end result is that the generated `en.pot` file contains translations for every string. This pot file is then accepted by transifex, allowing plurals to be properly translated. (after much trial and error together with Phil, we found that Transifex will not parse the imported pot file if only some of the strings have values)
d2-ui/interpretations currently uses this modified version of the extract.js script and it works as expected: https://github.com/dhis2/d2-ui/blob/master/packages/interpretations/scripts/extract.js
Would it be possible to release a beta to be tested with the DV app?
Here is an example of how plurals would look in code:
```
const replies = i18n.t( …
```

fix: set default value for all strings

---

cli/config/d2.config.app.js
cli/config/d2.config.lib.js

This fixes an issue when using cjs `require`s from a d2 lib package. Also added to the default app `d2.config` for consistency

fix: add file extension to default entrypoints in d2.config

---

cli/src/commands/publish.js
docs/scripts/publish.md

This adds a command that is pretty similar to `deploy`. It extracts some information from the built `appBundle`, however this uploads that bundle to App Hub instead of a DHIS2-instance. There's some code that is duplicated from `publish` (eg. `dumpHttpError`), could probably extract some of this to a common file. I didn't want to change more code than necessary.
This should mainly be used with app-platform apps, and it's thus very simple to use with a bundled app. However I added an escape hatch so that apps that are not migrated to the platform may use this to upload any arbitrary bundle to the app hub. That's why we have options like `appId`, `file` and `file-version`. There are not intended to be use for overriding the config from a built app, as we do not want discrepancies from the …

feat(publish): upload apps to App Hub

---

cli/src/commands/test.js

The [`updateSnapshot` parameter for the `test` command](https://github.com/dhis2/app-platform/blob/4e704c74bc5f02774f360fe65d8a684749affc02/cli/src/commands/test.js#L77-L82) was incorrectly referred to as `update` in its handler, hence it was impossible to set it to `true`.

fix: rename 'update' test command handler parameter to 'updateSnapshot'

---

cli/package.json
yarn.lock

This fixes an error that manifests as `Error: Cannot find module 'levenary'` when using CLI scripts - for some reason, the `@babel/preset-env` version required by `cli` resolves to a version that requires levenary, but apps using the CLI resolve `@babel/preset-env` to a version that does not use levenary. Bumping the version fixes the issue
Version 7.10.3 depends on 'levenary' (not shown in screenshot)
Note the difference from the CLI resolution. Version  7.14.7 does not include 'levenary' (and a few other packages), which causes the error(s)

fix(cli): bump @babel/preset-env

---

adapter/src/components/ErrorBoundary.js
adapter/src/components/styles/ErrorBoundary.style.js
adapter/src/index.js
examples/pwa-app/package.json
sw/src/index.js
sw/src/lib/registration.js

Adds an error boundary around the app to catch errors there, and enables the top-most error boundary to check for and apply service worker updates when 'refresh' is clicked

feat(adapter): smarter error boundaries

---

shell/public/service-worker.js

This adds a service worker that immediately takes control and tears down a previous service worker and then itself, which will fix apps that have rogue service workers.
This is a hold over until it will be handled by #550

feat(shell): add killswitch service worker

---

adapter/i18n/en.pot
adapter/src/components/ErrorBoundary.js
adapter/src/components/styles/ErrorBoundary.style.js

Improve error boundary by:
- Including error message in technical details drawer
- Add button to copy error message and stack trace to clipboard
- Remove min-width on error boundary mask to better support non-desktop devices
- Using `<button>` instead of `<div>` for drawer toggling
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4295266/125957814-33f9ec89-cb84-40b9-b395-265b6a8113af.png) | ![image](https://user-images.githubusercontent.com/4295266/125957777-f22f5ff5-13d8-439f-a8c5-ed8d03ce7412.png) |

feat: show error message in fatal error boundary and allow copying stack trace to clipboard

---

cli/src/commands/test.js

Usage: `d2-app-scripts test --jest-config ../path/to/jest.config.js`

feat(cli): add jestConfig option to test script

---

pwa/src/service-worker/utils.js

Previously, just the path was checked. This change allows checking the whole URL, which lets developers apply filters targeting domains and other parts of the URLs

fix: check whole URL against filter patterns

---

pwa/src/service-worker/recording-mode.js

Sometimes recordings hang due to an error with the indexedDB (`cannot read property 'put' of undefined`); catching that error and ending the recording lets the app be interactive again after the failed recording. I still haven't diagnosed why the error happens though 🤔

fix: catch errors in completeRecording

---

pwa/src/service-worker/recording-mode.js
pwa/src/service-worker/service-worker.js

This fixes the (seemingly) intermittent `cannot read property 'put' of undefined` issue at the end of recordings: apparently, [service workers will 'sleep'/terminate when they go idle](https://web.dev/service-worker-mindset/#watch-out-for-global-state), at which point they lose their global state (but this doesn't happen while the Chrome dev tools are open, so errors can slip by in development).  IndexedDB is reopened on demand if necessary to restore the `self.dbPromise` state.

fix: reopen indexedDB if global state resets

---

pwa/src/offline-interface/offline-interface.js
pwa/src/service-worker/recording-mode.js

Firefox can't handle any special objects in the `postMessage` API between service workers and clients, which causes those messages to go quietly unsent, which sometimes manifests as failed recordings getting stuck under a loading mask. This fix simplifies the payload for recording error messages so they work on firefox

fix: simplify message payload to be compatible with firefox

---

pwa/src/offline-interface/offline-interface.js
shell/package.json
yarn.lock

This fixes two related issues that happen in weird circumstances where the cached section entries in the IndexedDB and the sections' CacheStorage cache are out of sync, for example there is an IDB entry for a section but that section does not have a CacheStorage cache. I'm not sure how exactly this situation happens, but it seems like it happens sometimes in dev environments with unusual app lifecycles and service workers installing and updating frequently.
1. A section is only shown as cached if it has both an IDB entry and a CacheStorage cache associated with it
2. The `removeSection` function will return true if either of the IDB entry and CacheStorage cache are removed, which helps the runtime update its status accordingly
The app runtime dependency is also updated - weirdly, it's not …

fix: cached section status and removal given idb and cache discrepancies

---

cli/package.json

Set Jest's test environment to `node` for `cli-app-scripts` tests in order to save ~200ms per test that is otherwise wasted on initialising `jsdom`.

fix(cli): set test environment to node

---

adapter/src/components/ServerVersionProvider.js
adapter/src/index.js
shell/package.json
shell/src/App.js
yarn.lock

Uses latest UI version and adds `pwaEnabled` to the app config for the header bar to consume
Relates to https://jira.dhis2.org/browse/LIBS-48

feat: use new headerbar with online status indicator

---

shell/src/index.css

This adds two rules for the application root and portal root divs that
creates a new stacking context for each, this allows an app the freedom
to do pretty much whatever it wants with z-indexes, without affecting UI
components that render in a Portal.
It also allows other 3rd party libraries that rely on appending elements
to the DOM and modifying z-indexes to work better with our platform.
The isolation property has good support and should align nicely with our
supported browsers[1].
[1] https://caniuse.com/mdn-css_properties_isolation

fix(shell): create new stacking context for roots

---

shell/src/index.css
shell/src/index.js

This is a follow-up on #631 where we applied a CSS fix for layering issues. The fix was correct, but the CSS rules weren't being applied to the app because the `index.css` file was not being imported.
So we are now importing the file and the styles from `index.css` are being applied to the app. However, this file already included some style rules, and since they weren't being applied before (due to the file not being imported) it is safer to remove them, which I've done in 4376038.

fix: import index css file to apply global styles

---

pwa/src/offline-interface/offline-interface.js

Sometimes, when loading a PWA app for the first time while 'Update [SW] on reload' is checked in Chrome dev tools (in the Application tab), the app can get stuck in an infinite update loop which spams the 'Update' alert bars. This fix prevents that issue

fix(offline-interface): prevent infinite update loop in Chrome

---

pwa/src/service-worker/recording-mode.js

Also reduces unnecessary error logging
https://jira.dhis2.org/browse/TECH-675

fix(recording-mode): handle fulfilled requests after recording error

---

adapter/package.json
shell/package.json
yarn.lock

https://jira.dhis2.org/browse/LIBS-200. Updates to latest app-runtime release. Without this update a resolutions field is necessary to deduplicate the app-runtime to v3.
I've taken a look at the usage of the app-runtime in the app-platform. All seems compatible with v3. I think in a way the runtime and platform are coupled on major versions, as otherwise I suspect the app-platform provided app-runtime provider won't match the user's app-runtime provider (if they're on different major versions). In the current structure I find it hard to properly express that in semver without a lock-step monorepo release. Suggestions are welcome.

fix(dependencies): update app-runtime to v3 

---

adapter/src/components/LoginModal.js
cli/package.json
cli/src/commands/start.js
cli/src/lib/proxy.js
cli/src/lib/proxy.test.js
docs/_sidebar.md
docs/proxy.md
docs/scripts/start.md
docs/troubleshooting.md
yarn.lock

Introduces a proxy server that can be used to test remote instances without relying on cross-site cookies.
Usage:
```
d2-app-scripts start --proxy https://debug.dhis2.org/dev
```

feat(cli): instance proxy server

---

shell/public/index.html

As spotted by @mortenoh - 
>  If the manifest requires credentials to fetch, the crossorigin attribute must be set to use-credentials, even if the manifest file is in the same origin as the current page.
([source](https://web.dev/add-manifest/#link-manifest))
Adding `crossorigin="use-credentials"` to the manifest.json link tag prevents the syntax error at character 1 we see when the browser requests the manifest.  This was caused because the manifest request was redirecting to the login page, as the cookie was stripped from that request

fix: add crossorgin use-credentials to manifest.json link

---

shell/package.json

Allows yarn to dedupe ui for app installations.

fix(deps): allow range for app shell's ui dependency

---

.github/workflows/dhis2-deploy-netlify.yml
.github/workflows/dhis2-verify-lib.yml
shell/package.json
yarn.lock

Bump `react-scripts` to v5 to benefit from Webpack v5 and Jest v27.

chore: bump react-scripts

---

.github/workflows/dhis2-verify-lib.yml

Temporarily remove lint step from publish step requirements in order to be able to deploy https://github.com/dhis2/app-platform/pull/694 to beta tag.

fix: remove lint step from publish step requirements

---

adapter/package.json
shell/package.json
yarn.lock

BREAKING CHANGE: To prevent issues with multiple ui versions, we bump the major version of the app-platform libraries as well

chore(app shell and app adapter): update @dhis2/ui to ^8

---

cli/src/lib/proxy.js
cli/src/lib/proxy.test.js

A bug caused objects that had `property: null` to be converted to `{}`. This was causing the `data-entry-app` to crash, and was a pretty obscure bug to track down. The root of the issue is that `typeof null === 'object'`, and when using `_transform` with a default of `{}`, all `null`-properties were transformed to `{}`.

fix(proxy): ignore nulls in transformJsonResponse

---

cli/src/lib/generateManifests.js
cli/src/lib/paths.js
cli/src/lib/plugin/start.js
cli/src/lib/plugin/webpack.config.js
cli/src/lib/pwa/injectPrecacheManifest.js

Fixes [LIBS-346](https://dhis2.atlassian.net/browse/LIBS-346)
Generate `plugin_launch_path` in `manifest.webapp` which will be served by the backend in the `api/apps` API
Also includes a modified `entrypoints` map in the `d2.config.json` output:
```json
"entrypoints": {
"app": "index.html"
"plugin": "plugin.html"
}
```

feat: include plugin launch path plugin.html in built manifests [LIBS-346]

---

adapter/src/components/ServerVersionProvider.js
adapter/src/utils/api.js
cli/package.json
cli/src/commands/build.js
cli/src/lib/parseConfig.js
cli/src/lib/plugin/build.js
cli/src/lib/plugin/start.js
cli/src/lib/plugin/webpack.config.js
cli/src/lib/pwa/injectPrecacheManifest.js
pwa/src/service-worker/service-worker.js
pwa/src/service-worker/utils.js
yarn.lock

Currently the plugin and the app are sharing the same config -- this feels weird, but seems to work.
I'm noticing there are two versions of workbox in `yarn.lock` because it looks like there are strict version dependencies between the different workbox sub-packages -- I'll look into this too

feat(cli): add pwa to plugins

---

cli/src/lib/plugin/webpack.config.js
pwa/src/lib/registration.js
pwa/src/service-worker/service-worker.js

Addresses a few issues:
- SW registration URL wasn't working for plugins in development mode
- Static assets don't get cached at all in dev mode if the "don't cache" URL filter is `*`
Working on now:

fix(cli): improve plugin builds

---

cli/config/init.App.test.js
cli/config/init.entrypoint.js

The current App.js and App.test.js templates violate our current eslintReact style rules, such that a user initiating a new app platform app and installing default style rules will get style violations: 
```
...src/App.js
1:1   error  `react` import should occur after import of `@dhis2/d2-i18n`  import/order
16:28  error  Expected { after 'if' condition                               curly
17:30  error  Expected { after 'if' condition                               curly
...src/App.test.js
4:17  error  Missing file extension "js" for "./App"  import/extensions
```
This PR updates the formatting to comply with current rules

chore: update init files to comply with eslintReact style rules

---

adapter/src/components/Alerts.js
examples/pwa-app/src/components/VisualizationsList.js

Avoid cli-style warnings and clean up useEffect calls to make logic a bit cleaner

chore: fix cli-style useEffect exhaustive deps warnings

---

pwa/src/service-worker/service-worker.js

Pared down version of #757 
Addresses https://dhis2.atlassian.net/browse/TECH-1462  (partially)
* Switches SWR filter to handle just image files
* Passes 403 responses to client to show 'unauthorized' when online
Pairs well with https://github.com/dhis2/app-runtime/pull/1268 🥂

fix(pwa): file SWR filter & allow navigation 403s [LIBS-356] [LIBS-357]

---

shell/package.json
yarn.lock

Discussion: The pinned version here makes it slow to bump app-runtime versions in apps - bumping the version there creates duplicate versions if it's not the same as the shell, which takes another PR cycle. That will wait for another time though
This enables https://dhis2.atlassian.net/browse/TECH-1462

fix(deps): bump app-runtime to 3.6.1 [LIBS-356]

---

adapter/src/components/PWALoadingBoundary.js
pwa/src/offline-interface/offline-interface.js

https://dhis2.atlassian.net/browse/LIBS-374
Handles some common errors at the PWALoadingBoundary component and in the OfflineInterface itself so that the app is not blocked -- see the comment over `testSWAvailable()` in `offline-interface.js`
To test, try starting the PWA example (remember to run `yarn` and build the `adapter` and `pwa` packages), and opening it in private browsing in Firefox (where `navigator.serviceWorker` is undefined). You can also try to run an app on an insecure context too to see another error message

fix(pwa): handle sw errors [LIBS-374]

---

pwa/src/service-worker/utils.js

https://dhis2.atlassian.net/browse/LIBS-367
Results in correct client counts for PWA reloading purposes, otherwise all open tabs on this domain (even if they're not in scope of the SW) are returned

fix(pwa): only count clients in scope

---

shell/package.json

This bumps d2-i18n dependency (to avoid lost translations with i18next re-initialization (https://dhis2.atlassian.net/browse/DHIS2-14132))

fix: bump d2-i18n

---

cli/src/commands/test.js

Previously the path pattern would end up formatted incorrectly and would be useless, e.g. `--testRegex=Alerts` => `/A|l|e|r|t|s/`. This change makes the option work and we can filter tests! :D
I found the root of the error in the way the path patterns are built in the `jest-config` code: [`buildTestPathPattern()`](https://github.com/facebook/jest/blob/21a92711a22c7b6633909fd42a87499e179d80c2/packages/jest-config/src/normalize.ts#L391-L417)
It's surprising because [the CLI accepts a singular option](https://jestjs.io/docs/27.x/cli#--testpathpatternregex), but I guess since `@jest/core` isn't documented I shouldn't be that surprised 🤷‍♂️

fix(cli): fix `--testRegex` option on `test` command

---

cli/config/plugin.webpack.config.js

Fixes https://dhis2.atlassian.net/browse/LIBS-399
It seems like the `file-loader` is mangling the css file from maplibre-gl (which doesn’t need compiling, strangely) and outputting all kinds of nasty junk that doesn’t work, like:
* `static/media/javascript,__webpack_public_path__=….bin`
* `static/media/svg+xml;base64,ASD:LKFDNAJKSD….bin`
* other nasty `.bin` files
In the maps app, this caused an "Filename too long" error that prevented building the app, and `svg` icons were broken when run in dev mode.
Changing to the modern asset/resource "file loader" seems to fix it with no noticeable side effects.
This configuration was originally what I used when first making plugins, but I seem to remember there was a reason not to use it -- I think it had to do with CSS modules, but this config …

fix(plugins): fix file loader behavior [LIBS-399]

---

adapter/src/components/ServerVersionProvider.js
pwa/src/offline-interface/offline-interface.js
yarn.lock

New logic in the offline interface was causing this error: `[Offine interface] Cannot send service worker message - no service worker is controlling this page.`
This PR disables those actions in non-PWA apps and handles them in PWA apps in which the SW hasn't installed yet

fix: error in non-pwa apps [LIBS-315]

---

cli/src/lib/generateManifests.js
cli/src/lib/parseConfig.js

Addresses [LIBS-477](https://dhis2.atlassian.net/browse/LIBS-478), and also sneaks in the one-line fix for [LIBS-355](https://dhis2.atlassian.net/browse/LIBS-355)
Fixing [LIBS-479](https://dhis2.atlassian.net/browse/LIBS-479) is not so straightforward because of how the plugin builds depends on the app build, and needs some more work
[LIBS-478]: https://dhis2.atlassian.net/browse/LIBS-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIBS-355]: https://dhis2.atlassian.net/browse/LIBS-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIBS-479]: https://dhis2.atlassian.net/browse/LIBS-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIBS-477]: …

fix(plugins): omit launch paths when unused [LIBS-477]

---

cli/config/plugin.webpack.config.js

Addresses [LIBS-481](https://dhis2.atlassian.net/browse/LIBS-481)
This was happening because `process.env.NODE_ENV` seems to consistently be `development` during the `build` script for a reason I haven't discovered yet, despite [efforts to the contrary](https://github.com/dhis2/app-platform/blob/cc20ff17aa6ccd81a2862b7278b335c33be22dac/cli/src/lib/plugin/build.js#L3-L5)
Using `isProduction` here works because the plugin's `build` command manually sets the webpack env to 'production' [here](https://github.com/dhis2/app-platform/blob/cc20ff17aa6ccd81a2862b7278b335c33be22dac/cli/src/lib/plugin/build.js#L14-L18)
[LIBS-481]: https://dhis2.atlassian.net/browse/LIBS-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(plugins): inject precache manifest correctly [LIBS-481]

---

adapter/i18n/en.pot
adapter/package.json
adapter/src/components/AppWrapper.js
adapter/src/components/ErrorBoundary.js
adapter/src/components/ServerVersionProvider.js
adapter/src/components/styles/ErrorBoundary.style.js
adapter/src/index.js
cli/config/plugin.webpack.config.js
shell/package.json
shell/src/App.js
shell/src/PluginLoader.js
shell/src/PluginOuterErrorBoundary.js
yarn.lock

This PR is conceived in conjunction with [PR in app-runtime](https://github.com/dhis2/app-runtime/pull/1332) to provide plugin wrappers.
The main change in this code is adding PluginLoader in the app shell which sets up communication with the parent window. For the communication to work, PluginSender needs to be used in the app, otherwise, the communication will fail (the plugin would still load, so you can still build a plugin with this updated app shell and not use PluginSender if you do not want this communication channel, but do want a separate plugin build)
There is some additional updates in app/adapter for hoisting plugin alerts and errors.
**Some notes**
- Error boundaries are to be designed by Joe. For now, I have just modified the existing Error Boundary to make it work with a …

feat: implement plugin wrapper (receiver in plugin)

---

adapter/src/components/LoadingMask.js
shell/src/App.js

Requested by the Analytics team (@edoardo)
From @HendrikThePendric:
> Makes perfect sense to remove it. The main purpose of the translucent layer is to visually indicate that the content below is unreachable. If there is no content below, just showing a transparent layer is preferable.
More history: [slack thread](https://dhis2.slack.com/archives/C03TYMREXDL/p1678977406092729)

fix: make loading placeholders transparent

---

cli/config/plugin.webpack.config.js
cli/src/commands/build.js
cli/src/commands/start.js
cli/src/lib/plugin/build.js
cli/src/lib/plugin/start.js

Fixes [LIBS-485](https://dhis2.atlassian.net/browse/LIBS-485)
`process.env.NODE_ENV = 'development'` was leaking into the rest of the env. By fixing that, we can inject the precache manifest for plugins in production only, which fixes the error in dev
[LIBS-485]: https://dhis2.atlassian.net/browse/LIBS-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cli): fix envs to fix plugins in dev [LIBS-485]

---

pwa/src/offline-interface/offline-interface.js

Fixes a `TypeError: offlineInterface.ready is undefined` error in "no-SW conditions" like private browsing in Firefox or in insecure contexts (like HTTP)
Fixes https://dhis2.atlassian.net/browse/LIBS-499

fix(pwa): avoid crashing when SW is not available [LIBS-499]

---

cli/src/lib/paths.js

> I was facing this error when I run the d2 app scripts init pmtct to create a new app. Then I found this solution in the CoP: https://community.dhis2.org/t/rangeerror-maximum-call-stack-size-exceeded-error-when-i-run-d2-app-scripts-init-my-app/49023
> But` there we needa delete findYarnLock   function. Earlier today, when a was checking this function, I noticed that this function is in an infinite loop on windows systems because the base case inside this function is not verified only in windows.
`The line if(base==="/")  I think we are checking only for mac or linux OS 'cause in windows, is if(base==="C:\\") .`
---

fix: maximum call stack size exceeded at paths.js (findYarnLock function)

---

shell/src/PluginLoader.js

This adds logic to autoresize plugin wrapper components if no fixed height or width is specified. See also the corresponding change in app-runtime: https://github.com/dhis2/app-runtime/pull/1355.

feat: allow for auto resizing of plugins [LIBS-487]

---

cli/src/commands/start.js
cli/src/lib/plugin/start.js

https://dhis2.atlassian.net/browse/LIBS-503
Plugins are generally intended to be run inside other apps and therefore require other context to run -- it doesn't make sense to open up a browser and try to run it on its own

fix: don't open browser for plugins on start [LIBS-503]

---

adapter/src/utils/useLocale.js
adapter/src/utils/useLocale.test.js

fix: remove unused export for useLocale (and update tests)

---

adapter/i18n/en.pot
adapter/src/components/ErrorBoundary.js
adapter/src/components/LoginAppWrapper.js
adapter/src/index.js

Adds login-app-specific error boundary that shows button to redirect to "safe" login page:

feat: add redirect to safe login mode for login apps

---

adapter/package.json
shell/package.json
yarn.lock

The dependency loop for `@dhis2/app-service-data` is fixed by the change in the alpha branch of `@dhis2/app-runtime`, but `@dhis2/ui` depends on main release of `@dhis2/app-runtime` as well, which then ends up running into same the `app-runtime` loop -- hopefully this resolution works for NPM to fix the loop from the UI dependency on app runtime

fix(deps): resolution for app-runtime alpha

---

cli/config/plugin.webpack.config.js
cli/src/commands/start.js
cli/src/lib/plugin/start.js
docs/scripts/start.md
examples/pwa-app/d2.config.js

Addresses [LIBS-391](https://dhis2.atlassian.net/browse/LIBS-391) and [LIBS-392](https://dhis2.atlassian.net/browse/LIBS-392):
1. Runs a dev build with `yarn start` instead of a minified production build -- this was fixed by allowing multiple chunks to be made in the dev build
2. Allows starting the app and the plugin separately -- the default behavior is still the same to avoid a breaking change, but you can now run `yarn start --app` to start just the app or `yarn start --plugin` to start just the plugin
1. With the Vite changes, I think I will change the default to be to start just the app, then a user can pass the plugin flag to start just the plugin. It doesn't seem necessary to run both
Minified before & after:
New start script options:
[LIBS-391]: …

feat: start plugin and app separately [LIBS-391] [LIBS-392]

---

adapter/src/index.js
shell/src/PluginLoader.js

This does some clean up for issues noticed by @edoardo when testing plugins implementation:
- removes some styling on one of the outer divs for plugins (https://github.com/dhis2/app-platform/commit/e4b73d7bc95b40333cb1a9f0a9c6e70f612b3495). I have tested with auto resizing plugins, and the `flex` styling seems to not have an effect. The `fitContent` styling is not being applied anyway.
- removes `translucent` from plugin Loading layer (https://github.com/dhis2/app-platform/commit/997254f68a30461c460b3fc4a0dbdd6ccb6b88ee). We decided to do this before (https://github.com/dhis2/app-platform/pull/795), but it might have got lost in merge/redoing the plugin loading logic.
- fixes some invalid prop types checking (https://github.com/dhis2/app-platform/commit/6af10641e5953f3e0aab7b749273ba2d3dfb …

fix: clean up for plugins [LIBS-620]

---

adapter/src/components/LoginModal.js

This fixes an issue where the username and password were being encoded before being passed to api/login. 
I had copied some of the code from the old login logic, but that is using `Content-Type:application/x-www-form-urlencoded`, so requires encoding, whereas the post with json body, does not need that encoding 🤦‍♂️.
**Before**
payload like `{"username": "admin", "password":  "District1%23"}`
**After**
payload like `{"username": "admin", "password":  "District1#"}`

fix: do not encode username, password [LIBS-625]

---

adapter/i18n/en.pot
adapter/src/components/ErrorBoundary.js
adapter/src/components/styles/Button.style.js
adapter/src/components/styles/ErrorBoundary.style.js
shell/src/PluginOuterErrorBoundary.js

This PR implements styling for plugin error boundaries (see notes on https://dhis2.atlassian.net/issues/UX-136)
**Style note on screenshots**: note that the teal background / dotted blue line is styling from the app (that is the styling _around_ the plugin). The actual plugin error boundaries are the the grey boxes 9
General note: Off-ticket, I think Joe and I discussed that it might be better to not vertically center the plugin error message (because there's a greater likelihood that you would not see the error in the plugin if it's centered within the iframe). If we did actually want vertically centering, that's a small edit from this.
This is the error that you would get if something goes wrong within the plugin's code.
**Before**
**After**
-Note: The parent iframe needs to enable …

feat: cleanup plugin error boundary [UX-136]

---

shell/src/PluginLoader.js

See https://dhis2.atlassian.net/jira/software/c/projects/LIBS/issues/LIBS-634
This PR updates the styling around a plugin loaded by a shell:
- plugins that have fixed dimensions: app-shell loads the d2 without any divs/resizing logic
- plugins that have at least one dimension that can resize: load with extra wrapper divs and resizing logic.
Previously, plugins without resizing logic "skipped" the resizing logic (e.g. resizing observer not set up), but I kept (for consistency/simplicity) the extra wrapper divs in the expectation that they would not have issues. From a visual perspective, the wrapper divs don't do anything, but they are apparently preventing highcharts charts from executing their own resizing logic when used in dashboards.
Checked with dashboard/data visualizer, and this …

fix: fixed plugin dimensions [LIBS-634]

---

adapter/src/components/Alerts.js
adapter/src/components/__tests__/Alerts.test.js

This PR fixes a bug that was observed in the maps-app where multiple info alerts were added at approximately the same time. These alerts would then also hide at approximately the same time, but one alert would finish first and this would cause the other one to remount and restart its appear/show/hide lifecycle.
It took a long time to debug this issue and I found a few things wrong:
- It turned out that on occasion the `alertStackAlerts` was an empty array when it should have been populated. In the next render cycle, the array would have the expected alerts again, but because the array was empty during the previous render cycle, everything was remounting all the time.
- The fact that both the alerts-array from the alerts-manager and the local alerts array were stateful/reactive and because …

fix(alerts): ensure hiding works correctly and alerts are not re-added [DHIS2-15438]

---

adapter/src/components/AppWrapper.js

Part of [LIBS-633](https://dhis2.atlassian.net/browse/LIBS-633)
I noticed a small bug: when clicking on the "Retry" button in the plugin error boundary in the App Wrapper, if `skipPluginLogic` is set in `d2.config.js`, the action can fail with the error `clearPluginError is not a function` -- here's a fix by checking if that prop exists before executing
Before:
https://github.com/dhis2/app-platform/assets/49666798/03c2bbd4-af6c-4041-948f-e89dba1ab6a7
After:
https://github.com/dhis2/app-platform/assets/49666798/98608db2-e3b5-49a3-898b-e8ec869d18af
[LIBS-633]: https://dhis2.atlassian.net/browse/LIBS-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: plugin boundary retry if plugin logic is skipped [LIBS-633]

---

cli/package.json
yarn.lock

See [LIBS-641](https://dhis2.atlassian.net/browse/LIBS-641) and its related issue for more context (tl;dr: `i18next-scanner` has a dependency on `i18next` with `*` as the version, and `i18next` v21 broke it. Version 3.0.1+ of `i18next-scanner` adapts to the changes and makes it backwards-compatible, fixing the break it introduced for us)
We’re currently on v2, and the latest version is v4
* looking at the documentation, the breaking change in v3 of i18next-scanner  is just increasing the minimum node version to 10
* as far as I can tell, there isn't really a breaking change in v4, since an [error was introduced and then rolled back](https://github.com/i18next/i18next-scanner/issues/177#issuecomment-1178818448) – either way, it works in testing
* `i18next-scanner` now also seems to …

fix(deps): update i18next-scanner version to support old plurals format again [LIBS-641]

---

cli/package.json
yarn.lock

Follow-up on an issue introduced by [LIBS-641](https://dhis2.atlassian.net/browse/LIBS-641)
The problem I encountered:
When upgrading `@dhis2/cli-app-scripts` to v11.6.3 in the Data Visualizer app, i18n extraction broke with an error like `i18nextInstance.services.pluralResolver.getSuffixes is not a function`
The cause:
* I did some digging and found that v4 of `i18next-scanner` [introduced the use of this API](https://github.com/i18next/i18next-scanner/blame/f7203145829f2fce240e6660e03558027e1ba9e9/src/parser.js#L260), which is only available in `i18next` v20+ (although this change was not really documented, and because of `i18next-scanner`'s use of `"*"` for the version on their `i18next` dependency, maybe they're not even aware of it)
* `i18next-scanner`'s use of `"*"` for the version …

fix: use i18next-scanner v3 for better i18next compatibility

---

cli/config/init.entrypoint.js

See https://dhis2.atlassian.net/jira/software/c/projects/LIBS/issues/LIBS-644
I've updated to
- use `useDataQuery` rather than `<DataQuery>`
- added `i18n.t` wrapping on the error and loading text (I changed `...` to `Loading...`, so it doesn't look like we're just translating ellipses. I suppose that might be a valid translation as I don't know if other languages use ellipses in the same way, but it seems a bit confusing). I have changed this just to display best practice of translating strings.
- I've done a conditional return with error/loading that does not include the `<div className={classes.container}>` element. I've just done this for readability / mimic what we generally do in our apps. I thought repeating the div would be distracting as would refactoring to make it a common …

feat: update initial app code [LIBS-644]

---

cli/config/d2ConfigDefaults.js
cli/config/init/d2.config.app.js
cli/config/init/entrypoint.jsx

[LIBS-645](https://dhis2.atlassian.net/browse/LIBS-645)
Can be tested by checking out the branch and running `yarn d2-app-scripts init new-app` (note that the new app will use the version of `cli-app-scripts` on master): `direction: 'auto'` should be in `d2.config.js`, and setting an RTL language should display RTL direction (in the HTML, and the app text should look like "!Welcome to DHIS2")
The separation between boilerplate and config defaults can also be tested by commenting out `direction: 'auto'` in the config -- the current `direction: 'ltr'` default behavior should be restored
I think the version _after_ the Vite migration would be a good time to update the default direction to 'auto' to try to avoid _too_ many breaking changes with the migration
I also added the locale import to …

feat(init): set direction: 'auto' and import locales for new apps [LIBS-645]

---

cli/config/makeViteConfig.mjs

[LIBS-635](https://dhis2.atlassian.net/browse/LIBS-635)
Previously, apps were encountering this error:
```
The request url "/Users/kai/dev/dhis2/scheduler-app/node_modules/typeface-roboto/files/roboto-latin-500.woff2" is outside of Vite serving allow list.
- /Users/kai/dev/dhis2/scheduler-app/.d2/shell
- /Users/kai/dev/dhis2/scheduler-app/node_modules/vite/dist/client
Refer to docs https://vitejs.dev/config/server-options.html#server-fs-allow for configurations and more details.
The request url "/Users/kai/dev/dhis2/scheduler-app/node_modules/typeface-roboto/files/roboto-latin-700.woff2" is outside of Vite serving allow list.
The request url "/Users/kai/dev/dhis2/scheduler-app/node_modules/typeface-roboto/files/roboto-latin-400.woff2" is outside of Vite serving allow list.
```
As …

feat: hmr for .js files; fix file server for fonts [LIBS-635]

---

.github/workflows/dhis2-verify-lib.yml
adapter/src/components/ServerVersionProvider.js

See https://dhis2.atlassian.net/browse/LIBS-683
This provides a safeguard for the login app to default to an api version if the api version is missing from api/loginConfig (see linked slack discussion on the thread).
I think it would be better to fix this on the backend to reliably be able to get and return that api version, but this helps prevent users not being able to log in while we refine how to improve consistency of api/loginConfig.

fix: provide fallback api version [LIBS-683]

---

cli/src/commands/migrate/js-to-jsx.js

[LIBS-681](https://dhis2.atlassian.net/browse/LIBS-681)
Tested out in the Dashboard app, and the snapshots are indeed use for comparison -- the platform changes seem to have removed white space in some snaps as seen in the second screenshot below, for example.
One potential shortcoming of the script I noticed, however, is that it doesn't update file paths for things like mocked jest modules, resulting in errors like:
```sh
FAIL  src/components/Item/VisualizationItem/__tests__/Item.spec.jsx
● Test suite failed to run
Cannot find module '../../ItemHeader/DeleteItemButton.js' from 'src/components/Item/VisualizationItem/__tests__/Item.spec.jsx'
```
[LIBS-681]: https://dhis2.atlassian.net/browse/LIBS-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

feat: migrate snapshot files too [LIBS-681]

---

cli/src/lib/paths.js
docs/scripts/init.md
yarn.lock

Maybe an oversight from the TS template -- the paths to app-shell files will be static
(Also cleaned up a few things I noticed)

fix: correct app shell paths

---

cli/package.json

since it is no longer a transitive dependency of babel-preset after these changes in [@babel/preset-env@7.25](https://github.com/babel/babel/pull/16824)

fix: add @babel/plugin-syntax-dynamic-import as a direct dependency

---

cli/src/lib/publishVersion.js

The `maps-app` failed to uploading using `d2-app-scripts publish`. See eg. this run: https://github.com/dhis2/maps-app/actions/runs/11663969768/job/32473530177 . 
The truncated error made this quite hard to debug - I had to locally run this with a change in `node_modules` of the platform to see the actual error. So I made it dump the error regardless if it's axios-error.
The reason it failed was due to `axios`-defaults for `maxBodyLength`, which appears to be `10MB`. However the server should enforce the length, not the client. The server already does this and is currently configured to allow up to `20MB` (ref: https://github.com/dhis2/app-hub/blob/master/server/src/routes/v1/apps/handlers/createAppVersion.js#L36 )
Adds `maxContentLength: infinity; maxBodyLength: infinity` to hopefully …

fix(publishVersion): fix maxBodyLength when uploading to appHub

---

cli/src/lib/compiler/compile.js
yarn.lock

Library builds should always be .js files, as we strip types with `@babel/preset-typescript`
This was previously the case also for app files (see https://github.com/dhis2/app-platform/blob/master/cli/src/lib/compiler/compile.js#L20) but was removed because we no longer process app files with babel.

fix: normalize to .js extensions when compiling libraries

---

cli/src/commands/build.js
cli/src/lib/paths.js
yarn.lock

Instead of clobbering all of `./build`, just remove `./build/app` and `./build/bundle` before writing build output there.  The library compiler (`src/lib/compile.js`) already clears each module-specific output dir (`./build/es`, `./build/cjs`)
In the future we might not want to clobber all the bundle output either... sometimes it can be beneficial to keep different bundle versions.
We could optionally move these up to the beginning of the build process if we want them also the be cleared on unsuccessful builds.

fix: clear only required build dirs

---

adapter/package.json
docs/migration/v12.md
shell/package.json
yarn.lock

This version of app-runtime adds support for React 18; also used a new UI version because it's available

fix(deps): upgrade app-runtime and ui

---

docs/migration/v12.md

Quotes are needed around the title to allow the `:` character, and added a link -- tested locally in the dev portal:
https://github.com/user-attachments/assets/bbfebafd-51a1-455f-b8f8-472ee98666c7

docs(v12-migration): fix title and link

---

cli/src/commands/migrate/js-to-jsx.js

[LIBS-739](https://dhis2.atlassian.net/browse/LIBS-739)
Pretty similar logic to the other import replacer -- I used [AST explorer](https://astexplorer.net/) to help figure out the right nodes
This can be tested by running `../app-platform/cli/bin/d2-app-scripts migrate js-to-jsx` (and optionally `--debug`) in an app like Dashboard, if it's in a directory neighboring `app-platform`; then run `yarn test` to make sure the tests work. You can also inspect the mock imports; `src/components/__tests__/App.spec.js(x)` has several components imported:
[LIBS-739]: https://dhis2.atlassian.net/browse/LIBS-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update jest.mock imports with migrate js-to-jsx script

---

cli/config/makeViteConfig.mjs

This may be an expected default, but also makes it possible to use [Teamscale](https://docs.teamscale.com/howto/setting-up-profiler-tga/javascript/) to collect test coverage of Vite apps easily using a standalone build
(CRA added source maps by default)

feat(vite): add source maps to build

---

.github/workflows/generate-and-upload-bom.yml

Implements [SEC-60](https://dhis2.atlassian.net/browse/SEC-60)
---
1. Integration of Static Analysis Security Scanning Tool: Dependency Track: https://dtrack.security.dhis2.org/projects
2. Running every night so it won't bother Developers 
---
Dependency Track will scan the created SBOM and analyze for CVEs and open vulnerabilities.
Those reports will be evaluated by the security team and will be brought back to the dev teams if something crucial pops up
---
[SEC-60]: https://dhis2.atlassian.net/browse/SEC-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add workflow for dependency-track

---

pwa/src/service-worker/set-up-service-worker.js
shell/src/PluginLoader.jsx

[LIBS-762](https://dhis2.atlassian.net/browse/LIBS-762)
Would also contribute to [DHIS2-19160](https://dhis2.atlassian.net/browse/DHIS2-19160), but that can be handled on the back-end
1. Fixes correct `post-robot` target for plugins
2. ~Avoids getting redirected to Global Shell files instead of app files for `index.html` requests by the service worker~ -- dropped here in favor of a back-end fix
Tested by patching in the Data Visualizer app on the [Vite branch](https://github.com/dhis2/data-visualizer-app/pull/3266) -- before:
https://github.com/user-attachments/assets/41321339-0d92-4781-924a-0f1c6c2df8d7
After:
https://github.com/user-attachments/assets/971eec74-6e33-4e48-9636-8e2897bff784
[LIBS-762]: https://dhis2.atlassian.net/browse/LIBS-762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

fix(plugin-pwa): fix pwa installations and plugins in global shell

---

cli/src/commands/test.js

This surfaces the error that happens when running `yarn test`, otherwise the error is swallowed and we just get an unhelpful generic error message.
| Before | After |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/38ec8bf0-c1de-492c-af67-3a1df4c09d1c) | ![image](https://github.com/user-attachments/assets/00fa847e-9110-45da-9f53-78d3e780cd3d) |

fix: surface error when 'd2-app-scripts test' fails

---

cli/src/commands/build.js
cli/src/lib/i18n/extract.js
cli/src/lib/i18n/generate.js

This PR extracts and generates pot files for translations based on the manifest files. Right now, it extracts: App title, description and the names of the shortcuts.
Some design decisions:
- the key names are prefixed with `__MANIFEST_` to minimise the chance of a collision with an app translation key - they are also suffixed with a _context_ string to make it easier to understand where they are used in Transifex 
- the file generated is named `manifest.webapp.translations.json` and lives next to `manifest.webapp`
- the JSON format is an array of objects with an ID for the language, and a dictionary for the translation strings (after removing the `__MANIFEST_` prefix and the context suffix. This format just makes it easier to hydrate into a Java object on the server-side.
Sample pot file …

feat: extract and generate translation strings for manifest

---

pwa/src/lib/registration.js

If `register()` is called after the window `load` event, then the service worker won't get registered. This change checks for the [document ready state](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState) to check if it's loaded already

fix(pwa): ensure service worker registration triggers on page load

---

shell/public/index.html
shell/public/plugin.html

I ended up going for `_top` since this mirrors the normal default `_self` as closely as possible (more closely than `_blank`).

fix: set default target for links to _top so they work in global shell

---

.eslintrc.js
cli/config/templates/init-typescript/d2.config.app.ts
cli/config/templates/init-typescript/d2.config.lib.ts
cli/config/templates/init/d2.config.app.js
cli/config/templates/init/d2.config.lib.js
cli/src/index.d.ts
docs/config/d2-config-js-reference.md

this PR adds type definition and documentation for d2config, which then consumers can use to get type hints in their d2config even if they're not using TypeScript
NOTE: the video is outdated, now we need to import the config declaration from cli-app-scripts rather than app-runtime  `/** @type {import('@dhis2/cli-app-scripts').D2Config} */`
[d2config-types.webm](https://github.com/user-attachments/assets/bda03306-f4de-4a2c-bdf3-33f3d0b0c154)

feat: add typescript hints for d2 config

---

cli/package.json
yarn.lock

the last update https://github.com/dhis2/app-runtime/pull/1412 to expose TS types for Data Service broke the ES build. That's because of the `export type *` syntax used there which is not supported by the version of babel (and babel typescript preset) that we have bundled in app-platform.
Support for `export type *` (and TS 5.0 in general) was added in version [7.21.0](https://babeljs.io/blog/2023/02/20/7.21.0#typescript-50).
This PR updates these dependencies so that `yarn build` strips this syntax out of the ES builds (but keeps them in the generated types).
This shows the result of building the `app-runtime/data-service` initially with the outdated `babel` dependency, and then pointing to a version of the CLI that contains the update `babel` dependencies. …

fix: update babel/core and preset to support TS named exports

---

cli/src/commands/build.js
cli/src/lib/i18n/extract.js
cli/src/lib/i18n/generate.js

updates the format of the `manifest.web.translations` file generated for manifest translations.
related to https://github.com/dhis2/dhis2-core/pull/20246
implements https://dhis2.atlassian.net/browse/DHIS2-19189
```
[
{
"locale": "en",
"translations": {
"APP_TITLE": "Route Manager 1",
"APP_DESCRIPTION": "An app to manage route through the Route API",
"SHORTCUT_create a s": "create a s",
"SHORTCUT_list": "list"
}
},
{
"locale": "fr",
"translations": {
"APP_TITLE": "Le Route Manager",
"APP_DESCRIPTION": "",
"SHORTCUT_create": "Creer"
}
}
]
```
```
[
{
"locale": "en",
"shortcuts": {
"create a s": "create a s",
"list": "list"
},
"title": "Route Manager",
"description": ""
},
{
"locale": "fr",
"shortcuts": {
"create": "Creer"
},
"title": "Le Route Manager",
"description": ""
}
]
```

fix: update manifest tranlsations file format

---

adapter/package.json
shell/package.json
yarn.lock

I actually like higher UI version floors to make sure UI fixes get in for the app adapter and header bar, like this one: https://github.com/dhis2/ui/releases/tag/v10.7.1 
And, upgrading `cli-app-scripts` would upgrade the UI version in an app
Does the wider range fix some of the CLI installation warnings though?

fix(deps): higher UI version for header bar fixes

---

docs/config/extending-vite-config.md

When the annotation is correct, it adds a little header above the code block -- I had the wrong annotation. Here's what it looks like, manually editing it to `title` in the Developer Portal repo:

docs(vite-config): fix filename annotations on codeblock
