- cli/src/lib/compile.js
This is mostly just a re-org of code (plus support for production .map files in `yarn start` which we shouldn't ever need)
> chore: factor file copy task instead of duplicating logic

- cli/config/standard-libs.json
- cli/package.json
- docs/getting-started.md
- examples/simple-app/yarn.lock
- shell/adapter/package.json
- shell/adapter/yarn.lock
- shell/package.json
- shell/yarn.lock
- yarn.lock
Upgrade `@dhis2/app-runtime` to latest (v2.0)
> fix: upgrade app-runtime to 2.0

- cli/package.json
- cli/src/commands/init.js
- yarn.lock
Ensure that `node_modules`, `.d2`, and `src/locales` are in .gitignore
See #68
> fix: update gitignore on init

- shell/adapter/package.json
- shell/adapter/yarn.lock
Blocks updating the headerbar in usage-analytics-app.
> chore(deps): update ui-core and ui-widgets

- cli/config/standard-libs.json
- cli/package.json
- docs/bootstrapping.md
- shell/adapter/package.json
- shell/adapter/yarn.lock
- shell/package.json
- shell/yarn.lock
- yarn.lock
Resolves critical infinite rerender bug dhis2/app-runtime#253 and manual abort error dhis2/app-runtime#254
> fix: upgrade @dhis2/app-runtime to v2.0.4

- cli/src/commands/start.js
- cli/src/lib/shell/index.js
> fix: correctly set custom and fallback port overrides

- shell/.eslintrc.js
> fix(eslint): allow eslint to internally require the custom config

- cli/config/init.README.md
- cli/src/commands/init.js
- cli/src/lib/paths.js
Structure of README file is heavily inspired by the CRA's README file.
Closes #331
> fix(init): add a default README.md file

- adapter/package.json
- examples/simple-app/yarn.lock
- yarn.lock
DHIS2-8809 - escape regex special chars in search
DHIS2-8525, DHIS2-8723 - correctly select and use user locale and application title text
> fix: upgrade ui-widgets to 2.1.1 for proper translations

- adapter/src/components/Alerts.js
- adapter/src/components/AuthBoundary.js
- adapter/src/index.js
- examples/simple-app/src/Alerter.js
- examples/simple-app/src/App.js
- shell/package.json
- yarn.lock
This is the component that goes with the alerts-service. It simply displays the alerts from the alert context as `AlertBars` in an `AlertStack`. The `onHidden` callback on the `AlertBar` will execute the `onHidden` passed as an option to `useAlert` and also the `remove` function on the `alert`, which will remove the `alert` from the context. `onHidden` is called from the `AlertBar` **after** the hide-animation completes, so things are hiding smoothly.
I'll leave some small notes in the code as well.
> feat: introduce alerts component to show alerts as alert-bars in a stack

- shell/src/serviceWorker.js
Closes https://jira.dhis2.org/browse/LIBS-155
> fix: catch service worker unregistration rejection

- shell/public/index.html
- shell/src/index.js
- feat(portal-root): add root element for react portals
- refactor(template): rename the root element to dhis2 specific
> feat(portal-root): add root element for react portals

- .github/workflows/dhis2-verify-lib.yml
- package.json
- pwa/src/lib/registration.js
- pwa/src/offline-interface/offline-interface.js
- yarn.lock
This will allow Dependabot PRs to pass checks again.
> ci: update workflow

- pwa/src/lib/registration.js
After a hard-reload, PWA apps may malfunction because `navigator.serviceWorker.controller` becomes `null` (which inhibits `postMessage`s, among other things). This change to the registration logic will unregister, then reregister a service worker in the conditions after a hard reload. Note that this will cause another page refresh due to the controller change event.
See also [Jira](https://jira.dhis2.org/browse/TECH-676)
> fix(sw-registration): reregister SW after hard reload

- adapter/src/components/AppWrapper.js
- adapter/src/utils/useVerifyLatestUser.js
- shell/package.json
- yarn.lock
(WIP - awaiting app runtime function) 
Part of a three-part solution to clearing cached data that might be sensitive between users; see [this issue](https://jira.dhis2.org/browse/DHIS2-11759), this [header bar PR](https://github.com/dhis2/ui/pull/740), and this [runtime PR](https://github.com/dhis2/app-runtime/pull/1002).
> feat(adapter): clear sensitive caches on user-change

- adapter/src/components/AppWrapper.js
- adapter/src/utils/useVerifyLatestUser.js
- shell/package.json
- yarn.lock
Backport of #652; see also https://jira.dhis2.org/browse/TECH-682
> feat(adapter): clear sensitive caches on logout or user change (7.x)

- docs/scripts/test.md
Docs were out of date, this updates the help text for the test command
> docs: update help text for test command

- .eslintrc.js
- .github/workflows/dhis2-deploy-netlify.yml
- .github/workflows/dhis2-verify-lib.yml
- CHANGELOG.md
- adapter/package.json
- cli/package.json
- examples/pwa-app/package.json
- examples/simple-app/package.json
- package.json
- pwa/package.json
- shell/.eslintrc.js
- shell/package.json
- shell/public/service-worker.js
- yarn.lock
CI is failing because of the commit checks. Those are failing because of the long descriptions that semantic release generates and appends to the commit description. Not a problem though, won't fail once it's merged to master.
> chore: beta to stable

- cli/src/lib/plugin/webpack.config.js
New APIs needed here; fixes plugin builds in example apps
> fix(cli): update webpack plugin options

- shell/package.json
- yarn.lock
The pinning seemed unintentional in this PR: https://github.com/dhis2/app-platform/pull/761 
Result of discussion in this thread: https://dhis2.slack.com/archives/C02NHB92S2H/p1668443057797939
> fix(deps): bump platform deps and unpin

- shell/package.json
- yarn.lock
Addresses [LIBS-315](https://dhis2.atlassian.net/browse/LIBS-315)
[LIBS-315]: https://dhis2.atlassian.net/browse/LIBS-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(pwa): bump ui version for headerbar connection status [LIBS-315]

- adapter/package.json
- examples/pwa-app/package.json
- shell/package.json
- yarn.lock
Updated the dependencies on the `alpha` release to the main release
> fix: use main app-runtime release

- adapter/package.json
- shell/package.json
- yarn.lock
Part of [LIBS-587](https://dhis2.atlassian.net/browse/LIBS-587); see [this comment](https://dhis2.atlassian.net/browse/LIBS-587?focusedCommentId=194633) for reasoning
Follow-up of https://github.com/dhis2/app-runtime/pull/1377
[LIBS-587]: https://dhis2.atlassian.net/browse/LIBS-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(deps): avoid circular dependency

- adapter/package.json
- shell/package.json
- yarn.lock
Part of [LIBS-587](https://dhis2.atlassian.net/browse/LIBS-587)
This should resolve two observed dependency conflicts when installing the d2 cli
[LIBS-587]: https://dhis2.atlassian.net/browse/LIBS-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(deps): new versions of UI and app runtime

- adapter/package.json
- shell/package.json
- yarn.lock
Part of [LIBS-587](https://dhis2.atlassian.net/browse/LIBS-587)
Fixes errors for `@dhis2/cli-app-scripts` and `react`, fixed in `@dhis2/app-runtime` and `@dhis2/multi-calendar-dates`, respectively; the fix is confirmed on `@dhis2/cli@4.2.5-alpha.5`: [comment](https://dhis2.atlassian.net/browse/LIBS-587?focusedCommentId=195019)
[LIBS-587]: https://dhis2.atlassian.net/browse/LIBS-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(deps): upgrade @dhis2/app-runtime and @dhis2/ui for peer deps fixes [LIBS-587]

- cli/package.json
- pwa/package.json
- yarn.lock
> fix(deps): use exact version of workbox to avoid broken 6.6.1 version [alpha]

- adapter/package.json
- shell/package.json
- yarn.lock
update dhis2 ui minimum version
> chore: update to latest dhis2 ui

- docs/config/environment.md
Seems fairly straight-forward.
> docs: fix typo on -> or

- cli/src/commands/init.js
- yarn.lock
to point to master instead of alpha
-- this can wait to be merged until ready to release to master
> fix: update bootstrap script branch

- shell/src/PluginLoader.js
Backport of #902 
Ran it through some tests locally again:
https://github.com/user-attachments/assets/9660490a-a126-4aa9-a23f-530927e33c9d
> feat: plugin sizing updates [11.x]

- pwa/src/service-worker/set-up-service-worker.js
- shell/src/PluginLoader.js
[LIBS-762](https://dhis2.atlassian.net/browse/LIBS-762)
Backport of #910 
[LIBS-762]: https://dhis2.atlassian.net/browse/LIBS-762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: pwa installations and plugins for global shell [11.x]

- docs/migration/v12.md
Added the recording of the webinar to the docs.
Go ahead and merge after approval, as this is my last working day
> docs: add youtube

- yarn.lock
Squash-merging `beta` to `master` didn't trigger a release... hopefully this will
https://github.com/dhis2/app-platform/actions/runs/16251105900/job/45880949643#step:7:140
**UPDATE:** deduplicating deps seems to fix the problem in the comment below
> fix(deps): deduplicate dependencies

- docs/config/extending-vite-config.md
Woops -- it should be level 2, not 3
> docs(vite-config): fix header level
